### PR TITLE
Add CI

### PR DESCRIPTION
**Pull request by lalo**

### CODE REVIEW

**Comment by jackgerrits** [comment]
Since Coba is pure python manylinux should not be needed

**Comment by mrucker** [comment]
Hey also, I'm really ignorant about this kind of stuff with Python. Where is the service that would process this file? I've always assumed there's some online service we could setup to watch the repo and re-run the tests every time there is a commit. Is that what this is? In my mind I was thinking something like codecove (I know VW, matplotlib, and pandas use it) and Azure pipeline (also used by VW, matplotlib, and pandas).

**Comment by jackgerrits** [comment]
Github has their own automated testing service now which is free for open source projects. It is well integrated wit Github of course and is (in my opinion) probably the best experience at the moment. 

It looks like so far Eduardo is just experimenting. But eventually this could run tests, run linters and do type checking. This fun would run against each commit and PR. Having these automatic checks in place really helps you be confident the code is in a good state.

**Comment by lalo** [comment]
@mrucker hey Mark, can you merge this as-is? That should enable CI once its on the main branch. If not we can revert back or fix. Thanks

**Comment by mrucker** [comment]
Hey there. That's awesome. Yeah if any of my recent commits are conflicting I'm happy to do the merge. Just let me know. I've been working to get ready for the CI stuff over the holiday break by increasing test coverage. I'm doing one file a night, so we should have complete test coverage in about three more weeks. We're currently at about 87% coverage.

**Pull request merged**
